language: julia
os:
  - linux
  - osx
git:
  depth: 3
julia:
  - release
  - nightly
matrix:
  allow_failures:
    - julia: nightly
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.build("Example")'
  - if [ -f test/runtests.jl ]; then
      julia --check-bounds=yes -e 'Pkg.test("Example", coverage=true)';
    fi
  - julia -e 'cd(Pkg.dir("Example")); include(joinpath("doc","make.jl"));'
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
