language: julia
os:
  - linux
  - osx
git:
  depth: 3
julia:
  - release
  - nightly
matrix:
  allow_failures:
    - julia: nightly
after_script:
  - julia -e 'cd(Pkg.dir("StringParserPEG")); include(joindir("doc","make.jl"));'
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
